language: node_js
node_js:
   - 10.15.3
dist: trusty
sudo: required
addons:
   chrome: stable
git:
   quiet: true
   submodules: false
before_install:
   - echo "before_install steps"
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
   - export PATH="$HOME/.yarn/bin:$PATH"
install:
   - echo "install execution"
   - npm install -g @angular/cli@7.3.9
before_script:
   - echo "before_script has no steps"
   - npm install
script:
   - echo "script execution"
   - yarn lib:reset
   - ng test rmstek-sparklines  --karmaConfig=./projects/rmstek-sparklines/karma.conf.travisci.js
   - ng test living-style-guide --karmaConfig=./projects/living-style-guide/karma.conf.travisci.js
   - ng e2e
   - ng build living-style-guide --prod --base-href /rms-sparklines/ --deploy-url https://rodrigomattososilveira.github.io/rms-sparklines/
before_cache:
   - echo "before_cache has no steps"
cache: yarn
before_deploy:
   - echo "before_deploy steps - Tagging"
   - "./scripts/tag.sh"
deploy:
   - echo "Deploying to GitHub Pages"
   # Deploy the living styleguide to GitHub pages
   - provider: pages
     skip_cleanup: true
     local_dir: "./dist/living-style-guide"
     github_token: "$GITHUB_TOKEN"
     keep_history: true
     on:
        branch: issue-44-ng7
   # Deploy the component to nopm registry
   - echo "Publishing @rmstek-sparklines"
   - provider: script
     script: ./scripts/publish.sh "$(ls dist/rmstek-sparklines | grep tgz)"
     on:
        branch: issue-44-ng7
after_deploy:
   - echo "after_deploy has no steps"
after_script:
   - echo "after_script has no steps"
env:
   global:
      secure: jTW6SOWMJnKETwzF/jBO0e9FfAukxjH8RzNnhVCpQdSlOARTlPDFRhMwGzkvV2ArOvUCQ8PjxqBPkSXtQcXPEPDvY1ALnrAhdFYbYrjZ6CmFNQTr49mCKRImae7y8olVgdlK+MOvpnm07X33hVOqmkxHORwCNTaNCv868R9kIgKNHJOgNfsIchuNYHLKax3ruUP1qR9B7PEjVEbYMKxHLbR7noGro1lpWd3d210YwsVpE5zXDyc1o+LA6CUx4FOvBsTZjh9eVmafpnY9NBvF14agnLOTnBgAwfjaa+amBxxba4ixRB59NUzgDMA5a+A17M4AWS7pmbAVbjIIeGn56fE/7DhQZkCvMPB4BC2o8uFOCTlr5v9AWJlAVuxHnPXxi9OAnLtGXpDOZwp1q8RyAT0EsF+gNzXbBAfRn12zja/YWOHZlblpTAXhGwtktWkIgNuVMg/C2EQxFgiU/ym74NblY15wlFdsl0emuozT2OQw67COzo1VjNi6rw3uADgP/Vi2Anyaf0jYj797Wow6Pw+p19tjIAlbv1LU7nh89SnQlzwdMSTjoEweNp1cTVvgkDMJ6Lnonknvf8ZXU9AzcKKSujtjU3E7vgqf4aquLx3Os2VLsZHfMeUQThv+0cO9JXZiYulCDxKIGi6vE1KxS5i2n0D/hpSdwi9VpruqVhs=
