
language: node_js
node_js:
  - "10.15.3"
git:
  quiet: true
  submodules: false
branches:
  only:
  - issue-44-ng7-travis
  env:
    - DEPLOY_BRANCH: issue-44-ng7-travis
    - MASTER_BRANCH: master
    - GITHUB_PAGES_BRANCH: gh-pages
    - GH_EMAIL: r3850365@gmail.com
    - GH_NAME: RodrigoMattosoSilveira
    - CHROME_BIN: /usr/lib/chromium/chrome

#Job Lifecyle
# OPTIONAL Install apt addons --> not used
# OPTIONAL Install cache components --> not used
before_install:
- echo "before_install has no steps"

install:
- echo "install execution"
- npm install -g --silent @angular/cl

before_script:
- echo "before_script has no steps"

script:
- echo "script execution"
- ng build library
- ng build living-style-guide
- ng test library
- ng test living-style-guide
- ng e2e

before_cache:
- echo "before_cache nas no steps"

cache:
- npm

#after_success or after_failure
before_deploy: ./scripts/tag.sh

deploy:
  skip_cleanup: true
  local_dir: ./dist/living-styleguide
  provider: pages
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: issue-44-ng7-travis
after_deploy: echo "after_deploy nas no steps"
after_script: echo "after_script nas no steps"
