
language: node_js
git:
  quiet: true
  submodules: false
branches:
  only:
  - issue-44-ng7-travis


#Job Lifecyle
# OPTIONAL Install apt addons --> not used
# OPTIONAL Install cache components --> not used
before_install: echo "before_install has no steps"
install: yarn bootstrap
before_script: "before_script nas no steps"
script:
- yarn build
- ng test library
- ng test living-style-guide
- ng e2e
before_cache: echo "before_cache nas no steps"
cache: npm
#after_success or after_failure
before_deploy: ./scripts/tag.sh
deploy:
  skip_cleanup: true
  local_dir: ./dist/living-styleguide
  provider: pages
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: issue-44-ng7-travis
after_deploy: echo "after_deploy nas no steps"
after_script: echo "after_script nas no steps"
