
language: node_js
node_js:
  - "10.15.3"
dist: trusty
addons:
  chrome: stable
git:
  quiet: true
  submodules: false
branches:
  only:
  - issue-44-ng7-travis
  env:
    - DEPLOY_BRANCH: issue-44-ng7-travis
    - MASTER_BRANCH: master
    - GITHUB_PAGES_BRANCH: gh-pages
    - GH_EMAIL: r3850365@gmail.com
    - GH_NAME: RodrigoMattosoSilveira
    - CHROME_BIN: /usr/lib/chromium/chrome

#Job Lifecyle
# OPTIONAL Install apt addons --> not used
# OPTIONAL Install cache components --> not used
before_install:
- echo "before_install execution"
- # start your web application and listen on `localhost`
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
- #https://mxlinux.org/forum/viewtopic.php?t=47482
- sudo ln -s /var/lib/dbus/machine-id /etc/machine-id
- #https://github.com/travis-ci/travis-ci/issues/9024
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox

install:
- echo "install execution"
- npm install -g @angular/cli@7.3.9

before_script:
- echo "before_script execution"
- npm install

script:
- echo "script execution"
- ng build library
- ng build living-style-guide
- ng test library --watch=false
- ng test living-style-guide --watch=false
- ng e2e

before_cache:
- echo "before_cache nas no steps"

cache:
- npm

#after_success or after_failure
before_deploy: ./scripts/tag.sh

deploy:
  skip_cleanup: true
  local_dir: ./dist/living-styleguide
  provider: pages
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: issue-44-ng7-travis
after_deploy: echo "after_deploy nas no steps"
after_script: echo "after_script nas no steps"
