
language: node_js
node_js:
  - "10.15.3"
dist: trusty
sudo: required
addons:
  chrome: stable
git:
  quiet: true
  submodules: false
  
env:
  - DEPLOY_BRANCH: issue-44-ng7-travis
  - MASTER_BRANCH: master
  - GITHUB_PAGES_BRANCH: gh-pages
  - GH_EMAIL: r3850365@gmail.com
  - GH_NAME: RodrigoMattosoSilveira
  - CHROME_BIN: /usr/lib/chromium/chrome

branches:
  only:
  - issue-44-ng7-travis

#Job Lifecyle
# OPTIONAL Install apt addons --> not used
# OPTIONAL Install cache components --> not used
before_install:
  # https://github.com/kendaleiv/angular-testing/blob/master/.travis.yml
- echo "before_install steps"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install:
- echo "install execution"
- npm install -g @angular/cli@7.3.9

before_script:
- echo "before_script execution"
- npm install

script:
- echo "script execution"

- ng build library
- ng build living-style-guide

- ng test library --karmaConfig=./projects/living-style-guide/karma.conf.travisci.js
- ng test living-style-guide --karmaConfig=./projects/library/karma.conf.travisci.js

- ng e2e

before_cache:
- echo "before_cache has no steps"

cache:
- npm

#after_success or after_failure
before_deploy:
- echo "before_deploy steps"
- ./scripts/tag.sh

deploy:
  skip_cleanup: true
  local_dir: ./dist/living-styleguide
  provider: pages
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: issue-44-ng7-travis

after_deploy:
- echo "after_deploy has no steps"

after_script:
- echo "after_script has no steps"
